operator:
  scyllaDBVersion: "2025.1.2"
  # scyllaDBEnterpriseVersionNeedingConsistentClusterManagementOverride sets enterprise version
  # that requires consistent_cluster_management workaround for restore.
  # In the future, enterprise versions should be run as a different config instance in its own run.
  scyllaDBEnterpriseVersionNeedingConsistentClusterManagementOverride: "2024.1.11"
  scyllaDBUtilsImage: "docker.io/scylladb/scylla:2025.1.2@sha256:84e914792c61a7703ff616bf6ee6d4becbcf68845221bd2458fcab10ef64302c"
  scyllaDBManagerVersion: "3.6.0-dev-0.20250522.dbc9556f9"
  scyllaDBManagerAgentVersion: "3.6.0-dev-0.20250522.dbc9556f9"
  bashToolsImage: "registry.access.redhat.com/ubi9/ubi:9.5-1745854298@sha256:f4ebd46d3ba96feb016d798009e1cc2404c3a4ebdac8b2479a2ac053e59f41b4"
  grafanaImage: "docker.io/grafana/grafana:11.4.3@sha256:95eb8900c1e40e89b3e907094383b1c76c0c166ad5ec85e635de86f114aa7184" # Tracks scylla-monitoring/versions.sh GRAFANA_VERSION
  grafanaDefaultPlatformDashboard: "scylladb-2025.1/scylla-overview.2025.1.json"
  prometheusVersion: "v3.1.0" # Tracks scylla-monitoring/versions.sh PROMETHEUS_VERSION
operatorTests:
  scyllaDBVersions:
    updateFrom: "2025.1.1" # One patch lower than .operator.scyllaDBVersion
    upgradeFrom: "6.2.3" # One minor lower than .operator.scyllaDBVersion
  nodeSetupImage: "quay.io/scylladb/scylla-operator-images:node-setup-v0.0.3@sha256:c6b3de240cc5c884d5c617485bae35c51572cdfd39b6431d2e1f759c7d7feea1"
