// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apiscyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	versioned "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned"
	internalinterfaces "github.com/scylladb/scylla-operator/pkg/client/scylla/informers/externalversions/internalinterfaces"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/listers/scylla/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBManagerInformer provides access to a shared informer and lister for
// ScyllaDBManagers.
type ScyllaDBManagerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() scyllav1alpha1.ScyllaDBManagerLister
}

type scyllaDBManagerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScyllaDBManagerInformer constructs a new informer for ScyllaDBManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScyllaDBManagerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScyllaDBManagerInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScyllaDBManagerInformer constructs a new informer for ScyllaDBManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScyllaDBManagerInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaDBManagers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ScyllaV1alpha1().ScyllaDBManagers(namespace).Watch(context.TODO(), options)
			},
		},
		&apiscyllav1alpha1.ScyllaDBManager{},
		resyncPeriod,
		indexers,
	)
}

func (f *scyllaDBManagerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScyllaDBManagerInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scyllaDBManagerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiscyllav1alpha1.ScyllaDBManager{}, f.defaultInformer)
}

func (f *scyllaDBManagerInformer) Lister() scyllav1alpha1.ScyllaDBManagerLister {
	return scyllav1alpha1.NewScyllaDBManagerLister(f.Informer().GetIndexer())
}
