version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: wednesday
    time: '05:00' # UTC
  labels:
  - priority/important-longterm
  - kind/dependency-bump
  groups:
    gomod:
        applies-to: version-updates
        patterns:
          - "*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  labels:
  - priority/important-longterm
  - kind/dependency-bump
- package-ecosystem: pip
  directory: /docs
  schedule:
    interval: daily
    time: '05:00' # UTC
  allow:
  - dependency-name: sphinx-scylladb-theme
  - dependency-name: sphinx-multiversion-scylla
