version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: '06:00' # UTC
  labels:
  - priority/important-longterm
  - kind/dependency-bump
  groups:
    k8s.io:
      applies-to: version-updates
      patterns:
      - "k8s.io/*"
      - "sigs.k8s.io/*"
  rebase-strategy: "disabled"
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
    day: wednesday
    time: '06:00' # UTC
  labels:
  - priority/important-longterm
  - kind/dependency-bump
  groups:
    gomod:
      applies-to: version-updates
      exclude-patterns:
      - "k8s.io/*"
      - "sigs.k8s.io/*"
  rebase-strategy: "disabled"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  labels:
  - priority/important-longterm
  - kind/dependency-bump
  rebase-strategy: "disabled"
