apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylla
  labels:
    internal.scylla-operator.scylladb.com/delayed-volume-mount: ""
spec:
  agentVersion: 3.3.0@sha256:dc2684f51e961d88da5a8eac2d9f165cb7a960cbf91f67f49332e7224317c96b
  version: 6.1.1
  developerMode: true
  automaticOrphanedNodeCleanup: true
  sysctls:
    - fs.aio-max-nr=30000000
  scyllaArgs: --cluster-name="scylla-cluster"
  datacenter:
    name: us-east-1
    racks:
      - name: us-east-1a
        members: 1
        storage:
          capacity: 1Gi
          storageClassName: delayed
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi
