apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: scyllacluster-edit
rules:
- apiGroups:
  - scylla.scylladb.com
  resources:
  - scyllaclusters
  - scylladbmonitorings
  - scylladbdatacenters
  - scylladbclusters
  - scylladbmanagerclusterregistrations
  - scylladbmanagertasks
  verbs:
  - create
  - patch
  - update
  - delete
  - deletecollection
