apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: webhook-server
    app.kubernetes.io/name: webhook-server
  name: scylla-operator-webhook
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 5000
  selector:
    app.kubernetes.io/instance: webhook-server
    app.kubernetes.io/name: webhook-server
status:
  loadBalancer: {}
