apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webhook-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: webhook-server
      app.kubernetes.io/name: webhook-server
