apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: local-storage-provisioner
data:
  storageClassMap: |
    local-volumes:
       hostDir: /mnt/persistent-volumes/
       mountDir: /mnt/persistent-volumes/
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: xfs
       namePattern: "*"

