// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/typed/scylla/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScyllaDBManagers implements ScyllaDBManagerInterface
type fakeScyllaDBManagers struct {
	*gentype.FakeClientWithList[*v1alpha1.ScyllaDBManager, *v1alpha1.ScyllaDBManagerList]
	Fake *FakeScyllaV1alpha1
}

func newFakeScyllaDBManagers(fake *FakeScyllaV1alpha1, namespace string) scyllav1alpha1.ScyllaDBManagerInterface {
	return &fakeScyllaDBManagers{
		gentype.NewFakeClientWithList[*v1alpha1.ScyllaDBManager, *v1alpha1.ScyllaDBManagerList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scylladbmanagers"),
			v1alpha1.SchemeGroupVersion.WithKind("ScyllaDBManager"),
			func() *v1alpha1.ScyllaDBManager { return &v1alpha1.ScyllaDBManager{} },
			func() *v1alpha1.ScyllaDBManagerList { return &v1alpha1.ScyllaDBManagerList{} },
			func(dst, src *v1alpha1.ScyllaDBManagerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScyllaDBManagerList) []*v1alpha1.ScyllaDBManager {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScyllaDBManagerList, items []*v1alpha1.ScyllaDBManager) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
