// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/typed/scylla/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScyllaDBManagerClusters implements ScyllaDBManagerClusterInterface
type fakeScyllaDBManagerClusters struct {
	*gentype.FakeClientWithList[*v1alpha1.ScyllaDBManagerCluster, *v1alpha1.ScyllaDBManagerClusterList]
	Fake *FakeScyllaV1alpha1
}

func newFakeScyllaDBManagerClusters(fake *FakeScyllaV1alpha1, namespace string) scyllav1alpha1.ScyllaDBManagerClusterInterface {
	return &fakeScyllaDBManagerClusters{
		gentype.NewFakeClientWithList[*v1alpha1.ScyllaDBManagerCluster, *v1alpha1.ScyllaDBManagerClusterList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scylladbmanagerclusters"),
			v1alpha1.SchemeGroupVersion.WithKind("ScyllaDBManagerCluster"),
			func() *v1alpha1.ScyllaDBManagerCluster { return &v1alpha1.ScyllaDBManagerCluster{} },
			func() *v1alpha1.ScyllaDBManagerClusterList { return &v1alpha1.ScyllaDBManagerClusterList{} },
			func(dst, src *v1alpha1.ScyllaDBManagerClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScyllaDBManagerClusterList) []*v1alpha1.ScyllaDBManagerCluster {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScyllaDBManagerClusterList, items []*v1alpha1.ScyllaDBManagerCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
