apiVersion: v1
kind: Secret
metadata:
  name: dev-us-west-1
  namespace: remotekubernetescluster-credentials
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - cluster:
          certificate-authority-data: <kube-apiserver-ca-bundle>
          server: <kube-apiserver-address>
        name: dev-us-west-1
    contexts:
      - context:
          cluster: dev-us-west-1
          user: dev-us-west-1
        name: dev-us-west-1
    current-context: dev-us-west-1
    users:
      - name: dev-us-west-1
        user:
          token: <token-having-remote-operator-cluster-role>


