// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	scheme "github.com/scylladb/scylla-operator/pkg/client/scylla/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ScyllaDBManagersGetter has a method to return a ScyllaDBManagerInterface.
// A group's client should implement this interface.
type ScyllaDBManagersGetter interface {
	ScyllaDBManagers(namespace string) ScyllaDBManagerInterface
}

// ScyllaDBManagerInterface has methods to work with ScyllaDBManager resources.
type ScyllaDBManagerInterface interface {
	Create(ctx context.Context, scyllaDBManager *scyllav1alpha1.ScyllaDBManager, opts v1.CreateOptions) (*scyllav1alpha1.ScyllaDBManager, error)
	Update(ctx context.Context, scyllaDBManager *scyllav1alpha1.ScyllaDBManager, opts v1.UpdateOptions) (*scyllav1alpha1.ScyllaDBManager, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, scyllaDBManager *scyllav1alpha1.ScyllaDBManager, opts v1.UpdateOptions) (*scyllav1alpha1.ScyllaDBManager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*scyllav1alpha1.ScyllaDBManager, error)
	List(ctx context.Context, opts v1.ListOptions) (*scyllav1alpha1.ScyllaDBManagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *scyllav1alpha1.ScyllaDBManager, err error)
	ScyllaDBManagerExpansion
}

// scyllaDBManagers implements ScyllaDBManagerInterface
type scyllaDBManagers struct {
	*gentype.ClientWithList[*scyllav1alpha1.ScyllaDBManager, *scyllav1alpha1.ScyllaDBManagerList]
}

// newScyllaDBManagers returns a ScyllaDBManagers
func newScyllaDBManagers(c *ScyllaV1alpha1Client, namespace string) *scyllaDBManagers {
	return &scyllaDBManagers{
		gentype.NewClientWithList[*scyllav1alpha1.ScyllaDBManager, *scyllav1alpha1.ScyllaDBManagerList](
			"scylladbmanagers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *scyllav1alpha1.ScyllaDBManager { return &scyllav1alpha1.ScyllaDBManager{} },
			func() *scyllav1alpha1.ScyllaDBManagerList { return &scyllav1alpha1.ScyllaDBManagerList{} },
		),
	}
}
