// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	scyllav1alpha1 "github.com/scylladb/scylla-operator/pkg/api/scylla/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBManagerLister helps list ScyllaDBManagers.
// All objects returned here must be treated as read-only.
type ScyllaDBManagerLister interface {
	// List lists all ScyllaDBManagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1alpha1.ScyllaDBManager, err error)
	// ScyllaDBManagers returns an object that can list and get ScyllaDBManagers.
	ScyllaDBManagers(namespace string) ScyllaDBManagerNamespaceLister
	ScyllaDBManagerListerExpansion
}

// scyllaDBManagerLister implements the ScyllaDBManagerLister interface.
type scyllaDBManagerLister struct {
	listers.ResourceIndexer[*scyllav1alpha1.ScyllaDBManager]
}

// NewScyllaDBManagerLister returns a new ScyllaDBManagerLister.
func NewScyllaDBManagerLister(indexer cache.Indexer) ScyllaDBManagerLister {
	return &scyllaDBManagerLister{listers.New[*scyllav1alpha1.ScyllaDBManager](indexer, scyllav1alpha1.Resource("scylladbmanager"))}
}

// ScyllaDBManagers returns an object that can list and get ScyllaDBManagers.
func (s *scyllaDBManagerLister) ScyllaDBManagers(namespace string) ScyllaDBManagerNamespaceLister {
	return scyllaDBManagerNamespaceLister{listers.NewNamespaced[*scyllav1alpha1.ScyllaDBManager](s.ResourceIndexer, namespace)}
}

// ScyllaDBManagerNamespaceLister helps list and get ScyllaDBManagers.
// All objects returned here must be treated as read-only.
type ScyllaDBManagerNamespaceLister interface {
	// List lists all ScyllaDBManagers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*scyllav1alpha1.ScyllaDBManager, err error)
	// Get retrieves the ScyllaDBManager from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*scyllav1alpha1.ScyllaDBManager, error)
	ScyllaDBManagerNamespaceListerExpansion
}

// scyllaDBManagerNamespaceLister implements the ScyllaDBManagerNamespaceLister
// interface.
type scyllaDBManagerNamespaceLister struct {
	listers.ResourceIndexer[*scyllav1alpha1.ScyllaDBManager]
}
