# Version information
scyllaImage:
  tag: 5.4.3
agentImage:
  tag: 3.3.0

# Cluster information
developerMode: true
datacenter: us-east-1
racks:
- name: us-east-1b
  members: 2
  storage:
    capacity: 5Gi
    storageClassName: scylladb-local-xfs
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
  placement:
    tolerations:
    - key: scylla-operator.scylladb.com/dedicated
      operator: Equal
      value: scylladb-clusters
      effect: NoSchedule
