apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: scylladb-nodepool-1
spec:
  localDiskSetup:
    loopDevices:
    - name: persistent-volumes
      imagePath: /var/lib/persistent-volumes.img
      size: 80Gi
    filesystems:
    - device: /dev/loops/persistent-volumes
      type: xfs
    mounts:
    - device: /dev/loops/persistent-volumes
      mountPoint: /var/lib/persistent-volumes
      unsupportedOptions:
      - prjquota
  sysctls:
  - name: fs.aio-max-nr
    value: "30000000"
  - name: fs.file-max
    value: "9223372036854775807"
  - name: fs.nr_open
    value: "1073741816"
  - name: fs.inotify.max_user_instances
    value: "1200"
  - name: vm.swappiness
    value: "1"
  - name: vm.vfs_cache_pressure
    value: "2000"
  placement:
    nodeSelector:
      scylla.scylladb.com/node-type: scylla
    tolerations:
    - effect: NoSchedule
      key: scylla-operator.scylladb.com/dedicated
      operator: Equal
      value: scyllaclusters
