apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <eks_cluster_name>
  region: <eks_region>

availabilityZones:
- <eks_zone>

nodeGroups:
- name: scylla-pool
  instanceType: i4i.2xlarge
  desiredCapacity: 3
  labels:
    scylla.scylladb.com/node-type: scylla
  taints:
    scylla-operator.scylladb.com/dedicated: "scylladb-clusters:NoSchedule"
  ssh:
    allow: true
  kubeletExtraConfig:
    cpuManagerPolicy: static
  availabilityZones:
  - <eks_zone>

- name: cassandra-stress-pool
  instanceType: c4.2xlarge
  desiredCapacity: 4
  labels:
    pool: "cassandra-stress-pool"
  taints:
    scylla-operator.scylladb.com/dedicated: "cassandra-stress:NoSchedule"
  ssh:
    allow: true

- name: monitoring-pool
  instanceType: i3.large
  desiredCapacity: 1
  labels:
    pool: "monitoring-pool"
  ssh:
    allow: true
